language: node_js
node_js: 
  - 6

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test

stages:
  - lint
  - test
